kind = "web"
previewPath = "/"
title = "Todo App"
version = "1.0.0"
id = "artifacts/todo-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25230

[services.development]
run = "/nix/store/51gywl5jn4nna7al9waj142pw4vfhy0k-nodejs-22.19.0/bin/npm install && /nix/store/51gywl5jn4nna7al9waj142pw4vfhy0k-nodejs-22.19.0/bin/npm run dev"

[services.env]
PORT = "25230"
