name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        run: docker build -t todo-app:latest -t todo-app:${{ github.sha }} .

      - name: Verify image exists
        run: docker images | grep todo-app